# Generated by Django 4.0.1 on 2022-03-12 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=50)),
                ('role', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='importantDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('document', models.FileField(upload_to='')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.login')),
            ],
        ),
    ]
